from pathlib import Path
import ast

import pytest

from nomina_view import calcular_nomina_completa


ROOT = Path(__file__).resolve().parents[1]


def test_nomina_mensual_2026():
    result = calcular_nomina_completa(50_000, "mensual", 2026)
    assert result["sueldo_bruto"] == 50_000
    assert result["sfs_empleado"] == 1_520
    assert result["afp_empleado"] == 1_435
    assert result["isr"] == 1_854
    assert result["neto_pagar"] == 45_191


def test_nomina_quincenal_prorratea_todas_las_deducciones():
    result = calcular_nomina_completa(50_000, "quincenal", 2026)
    assert result["sueldo_bruto"] == 25_000
    assert result["sfs_empleado"] == 760
    assert result["afp_empleado"] == 717.5
    assert result["isr"] == 927
    assert result["neto_pagar"] == 22_595.5
    assert result["sueldo_bruto"] - result["neto_pagar"] == pytest.approx(
        result["sfs_empleado"] + result["afp_empleado"] + result["isr"]
    )


def test_nomina_rechaza_ano_sin_parametros_verificados():
    with pytest.raises(ValueError):
        calcular_nomina_completa(50_000, "mensual", 2025)


def test_nomina_rechaza_arl_fuera_del_rango_configurable():
    with pytest.raises(ValueError):
        calcular_nomina_completa(50_000, "mensual", 2026, arl_tasa=0.02)


def test_nomina_usa_escala_isr_2026_verificada():
    result = calcular_nomina_completa(100_000, "mensual", 2026)
    assert result["isr"] == 12_105.44
    assert result["neto_pagar"] == 81_984.56


def test_no_hay_credenciales_maestras_en_codigo():
    forbidden = [
        "APP_PASSWORD",
        "master_pin",
        "PIN Maestro",
        "str(clave_guardada).strip() ==",
    ]
    files = [
        path for path in ROOT.rglob("*.py")
        if "tests" not in path.parts and "__pycache__" not in path.parts
    ]
    combined = "\n".join(path.read_text(encoding="utf-8") for path in files)
    for marker in forbidden:
        assert marker not in combined


def test_migracion_invalida_credenciales_heredadas_aunque_sean_obligatorias():
    sql = (
        ROOT / "supabase/migrations/202607250001_secure_foundation.sql"
    ).read_text(encoding="utf-8")
    drop_constraint = (
        "alter table public.configuracion_sistema alter column clave drop not null"
    )
    clear_value = (
        "update public.configuracion_sistema set clave=null where clave is not null"
    )
    assert drop_constraint in sql
    assert clear_value in sql
    assert sql.index(drop_constraint) < sql.index(clear_value)
    assert "alter table public.usuarios alter column %I drop not null" in sql


def test_dgii_no_tiene_emision_operativa():
    ecf = (ROOT / "facturacion_electronica_view.py").read_text(encoding="utf-8")
    credit_notes = (ROOT / "notas_credito_view.py").read_text(encoding="utf-8")
    helpers = (ROOT / "helpers.py").read_text(encoding="utf-8")
    assert "pkcs12.load_key_and_certificates" not in ecf
    assert "XML e-CF Oficial" not in ecf
    assert "Producción (Facturación Real)" not in ecf
    assert "TrackID\": \"TRK-" not in ecf
    assert "consumir_ncf_siguiente" not in credit_notes
    assert "consumir_ncf_siguiente" not in helpers
    assert "insertar(" not in credit_notes
    assert "no crea, numera, firma, registra ni" in credit_notes


def test_api_critica_es_transaccional_y_recalcula():
    sql = (ROOT / "supabase/migrations/202607250002_transactional_api.sql").read_text(
        encoding="utf-8"
    )
    assert "api_registrar_venta" in sql
    assert "INVALID_ITEM_QUANTITY" in sql
    assert "PAYMENT_MISMATCH" in sql
    assert "for update" in sql.lower()
    assert "inventario_consumos" in sql
    assert "public.api_anular_venta" in sql
    assert "public.api_abrir_caja" in sql
    assert "public.api_cerrar_caja" in sql
    assert "DGII_EDUCATIONAL_ONLY" in sql


def test_api_mantenimiento_cubre_cuenta_compra_nomina_y_cierre():
    foundation = (
        ROOT / "supabase/migrations/202607250001_secure_foundation.sql"
    ).read_text(encoding="utf-8")
    sql = (
        ROOT / "supabase/migrations/202607250003_maintenance_and_accounting_api.sql"
    ).read_text(encoding="utf-8")
    for function_name in [
        "api_reemplazar_cuenta_abierta",
        "api_registrar_compra_producto",
        "api_registrar_nomina",
        "api_cerrar_periodo",
    ]:
        assert function_name in sql
    assert "EMPLOYEE_ARL_RATE_REQUIRED" in sql
    assert "DUPLICATE_PAYROLL_PAYMENT" in sql
    assert "v_emp.id::text" in sql
    assert "v_compra_id uuid" in sql
    assert "returning id into v_compra_id" in sql
    assert "id bigint generated by default as identity primary key" in foundation
    assert "compra_id uuid" in foundation
    assert "lote_id bigint references public.inventario_lotes(id)" in foundation
    assert "usuario_id text" in foundation
    first_tenant_columns = foundation.index(
        "-- Columnas mínimas requeridas por la API segura"
    )
    first_product_columns = foundation.index(
        "alter table if exists public.productos add column"
    )
    tenant_column_block = foundation[first_tenant_columns:first_product_columns]
    assert "'inventario_lotes'" in tenant_column_block
    assert "update public.inventario_lotes il" in foundation
    assert "set empresa_id=c.empresa_id" in foundation
    assert "set empresa_id=p.empresa_id" in foundation
    assert foundation.count(
        "'alter table public.%I add column if not exists empresa_id text'"
    ) >= 4


def test_rls_no_contiene_politica_publica_total():
    sql = "\n".join(
        path.read_text(encoding="utf-8")
        for path in (ROOT / "supabase/migrations").glob("*.sql")
    ).lower()
    assert "using (true)" not in sql
    assert "with check (true)" not in sql
    assert "from anon" in sql
    assert "has_tenant_access" in sql
    assert "registrar_venta_transaccional" in sql
    assert (
        "revoke all on function %i.%i(%s) from public, anon, authenticated"
        in sql
    )
    assert "usuario_id=auth.uid()" in sql
    assert "la pertenencia a una empresa no concede por sí sola" in sql


def test_copias_de_compatibilidad_son_minimas():
    for folder in ("core", "modules"):
        for path in (ROOT / folder).glob("*.py"):
            if path.name == "__init__.py":
                continue
            assert len(path.read_text(encoding="utf-8").splitlines()) <= 5


def test_modulos_canonicos_no_provocan_importacion_circular():
    for name in ("app.py", "db.py", "auth.py", "utils.py", "helpers.py"):
        code = (ROOT / name).read_text(encoding="utf-8")
        assert "from core.db import" not in code
        assert "from core.auth import" not in code
        assert "from core.utils import" not in code
        assert "from core.helpers import" not in code

    core_db = (ROOT / "core/db.py").read_text(encoding="utf-8")
    assert "from db import _df_actual" not in core_db
    assert "from db import _pii_mask" not in core_db


def test_migraciones_no_contienen_operaciones_destructivas_de_esquema():
    for path in (ROOT / "supabase/migrations").glob("*.sql"):
        sql = path.read_text(encoding="utf-8").lower()
        assert "drop table" not in sql
        assert "truncate " not in sql
        assert sql.count("$$") % 2 == 0
        assert sql.strip().startswith("--")
        assert sql.strip().endswith("commit;")


def test_edge_functions_exigen_mfa_y_service_role_solo_en_servidor():
    for path in (ROOT / "supabase/functions").glob("*/index.ts"):
        code = path.read_text(encoding="utf-8")
        assert "MFA_AAL2_REQUIRED" in code
        assert 'Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")' in code
        assert "getUser(token)" in code
    application_code = "\n".join(
        (ROOT / name).read_text(encoding="utf-8")
        for name in ["app.py", "db.py", "auth.py", "helpers.py", "api_client.py"]
    )
    assert "SUPABASE_SERVICE_ROLE_KEY" not in application_code
    assert "SUPABASE_SERVICE_KEY" not in application_code
    invite = (
        ROOT / "supabase/functions/invite-user/index.ts"
    ).read_text(encoding="utf-8")
    provision = (ROOT / "scripts/provision_owner.py").read_text(encoding="utf-8")
    assert "id: authUserId" in invite
    assert '"id": user_id' in provision


def test_documentacion_declara_staging_y_limite_dgii():
    readme = (ROOT / "README.md").read_text(encoding="utf-8").lower()
    guide = (ROOT / "GUIA_PUBLICACION.md").read_text(encoding="utf-8").lower()
    assert "candidato para **staging**" in readme
    assert "no genera, firma, valida ni envía" in readme
    assert "empresa a y empresa b" in guide


def test_helpers_no_ejecuta_login_durante_importacion():
    tree = ast.parse((ROOT / "helpers.py").read_text(encoding="utf-8"))
    top_level_calls = [
        node
        for node in tree.body
        if isinstance(node, ast.If)
        and isinstance(node.test, ast.UnaryOp)
        and isinstance(node.test.op, ast.Not)
        and isinstance(node.test.operand, ast.Call)
        and isinstance(node.test.operand.func, ast.Name)
        and node.test.operand.func.id == "login_simple"
    ]
    assert top_level_calls == []


def test_permisos_sql_coinciden_con_la_aplicacion():
    sql = (ROOT / "supabase/migrations/202607250001_secure_foundation.sql").read_text(
        encoding="utf-8"
    )
    for permission in [
        "puede_editar_productos",
        "puede_registrar_compras",
        "puede_registrar_gastos",
    ]:
        assert permission in sql
    assert (
        "pagos_empleados add column if not exists empleado_id text"
        in sql
    )


def test_no_hay_rutas_privadas_de_la_computadora_en_la_aplicacion():
    application_code = "\n".join(
        path.read_text(encoding="utf-8")
        for path in ROOT.rglob("*.py")
        if "tests" not in path.parts and "__pycache__" not in path.parts
    )
    assert "/Users/user/Desktop/" not in application_code


def test_hay_una_sola_entrada_activa_para_login_y_academia_dgii():
    helpers_tree = ast.parse((ROOT / "helpers.py").read_text(encoding="utf-8"))
    accounting_tree = ast.parse(
        (ROOT / "contabilidad_view.py").read_text(encoding="utf-8")
    )
    helper_names = [
        node.name for node in helpers_tree.body if isinstance(node, ast.FunctionDef)
    ]
    accounting_names = [
        node.name for node in accounting_tree.body if isinstance(node, ast.FunctionDef)
    ]
    assert helper_names.count("login_simple") == 1
    assert accounting_names.count("render_reportes_dgii") == 1


def test_no_se_puede_retirar_el_ultimo_admin_de_una_empresa():
    sql = (ROOT / "supabase/migrations/202607250001_secure_foundation.sql").read_text(
        encoding="utf-8"
    )
    assert "protect_last_tenant_admin" in sql
    assert "TENANT_MUST_KEEP_ONE_ACTIVE_ADMIN" in sql


def test_edicion_de_permisos_conserva_flags_no_visibles():
    auth_code = (ROOT / "auth.py").read_text(encoding="utf-8")
    assert "permisos = dict(defaults_dict)" in auth_code
    for permission in [
        "puede_ver_dashboard",
        "puede_ver_reportes",
        "puede_ver_utilidad",
        "puede_configurar",
    ]:
        assert f'permisos["{permission}"]' in auth_code
